FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip \
  python3-dev \
  git \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 --install upgrade pip3


# Copy requirement library list
COPY requirements.txt .

RUN pip3 install --no-cache-dir --root-user-action=ignore -r requirements.txt

# Copy everything
COPY . .

RUN useradd -m devuser
USER devuser
